Metrics/BlockLength:
  Max: 400
Metrics/AbcSize:
  Max: 400
Metrics/CyclomaticComplexity:
  Max: 400
Metrics/MethodLength:
  Max: 400
Metrics/PerceivedComplexity:
  Max: 400
Metrics/LineLength:
  Max: 120
Security/Eval:
  Enabled: false
